
################################################################################
# builder
################################################################################
FROM ubuntu:20.04 as builder

RUN sed -i 's#http://archive.ubuntu.com/ubuntu/#mirror://mirrors.ubuntu.com/mirrors.txt#' /etc/apt/sources.list;

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl ca-certificates gnupg patch

# nodejs
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs

# yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn

# build frontend
COPY /docker-ubuntu-vnc-desktop/web /src/web
RUN cd /src/web \
    && apt update \
    && apt install -y yarn
RUN sed -i 's#app/locale/#novnc/app/locale/#' /src/web/dist/static/novnc/app/ui.js

################################################################################
# copy binary back to HOST base system
################################################################################

FROM ubuntu:20.04 as system
COPY --from=builder /src/web/dist/ /storage/
ENTRYPOINT ["/usr/bin/cp -R /storage/* /usr/local/lib/web/frontend/.", ]